let gameSequence = [];
let userSequence = [];
let highestScore = 0;
//Note that the size of the gameSequene and theuserSequence is equal to
//the current level played by the user

let btns = ["red", "green", "yellow", "purple"];
//should be in the correct sequence

let started = false;
let level = 0;

//****************************Game started here************************************ */
document.addEventListener("keypress", function () {
  console.log("Game started");
  if (started == false) {
    console.log("Game is started");
    started = true;

    levelUp();
  }
});

let h2 = document.querySelector("h2");
let body = document.querySelector("body")
function levelUp() {
  //step1: level++
  level++;
  h2.innerText = `Level ${level}`;

  //choose the random button and then flash
  let randomIndex = Math.floor(Math.random() * 4);
  let randomColor = btns[randomIndex];
  let randombtn = document.querySelector(`.${randomColor}`);

  // console.log(randomIndex);
  // console.log(randomColor);
  // console.log(randombtn);

  //***************************** */
  gameSequence.push(randomColor);
  console.log(gameSequence);
  btnFlash(randombtn);
}

//we will give the different flash color to the flash generated by the user and flash generated by the computer during the levelUp
function btnFlash(btn) {
  btn.classList.add("flash");
  setTimeout(function () {
    btn.classList.remove("flash");
  }, 150);
}

//userFlash function:
//when user presses the button then the flash will be different
function userFlash(btn) {
  btn.classList.add("userFlash");
  setTimeout(function () {
    btn.classList.remove("userFlash");
  }, 150);
}

//to check whether the color pressed by the user
//matches with the color in the gameSequence or not
function checkAns(index) {
  console.log(`current level: ${level}`);
  // let index = level-1;

  if (userSequence[index] == gameSequence[index]) {
    console.log("same value");
    //if value is same then there are 2 conditions
    //1. we are i the middle of sequence
    //2. we are at the end of the sequence

    //for case 2
    if (userSequence.length == gameSequence.length) {
      userSequence.length = 0;
      //we have to empty the userSequence array after successfull level completion
      setTimeout(levelUp, 1000);
      //when all the game and user sequence matches then,
      //to understand where the computer has started the new color, we have used this setTimeout function
    }
  } else {    
    //if we press the wrong button then.....
    body.classList.add("wrong");
    setTimeout(function () {
      body.classList.remove("wrong");
    }, 150);

    if(highestScore<(level-1)){
        highestScore=level-1;
        h2.innerHTML = `Wrong Button Pressed. Game Over!<br/>congradulations!!! You Got the highest score of ${highestScore}<br/>Press any key to start`;
    reset();
    }else{
    //as the sequences doesn't match it means wrong color pressed by the user
    h2.innerHTML = `Wrong Button Pressed. Game Over! Your score was <b>${level-1}</b><br/>Highest Score: ${highestScore} <br/> Press any key to start`;
    //after the game is reStarted we need to reset all the arays and the other conditions
    reset();}
    //reset function is called to reset all the condition
  }
}

//action that will be taken when we press the button
function btnPress() {
  console.log("Buton was pressed");
  // console.log(this)//what exctly has been pressed
  let btn = this;
  userFlash(btn);

  //we will extract the id of the button that has been pressed
  userColor = btn.getAttribute("id");
  console.log(userColor);
  userSequence.push(userColor);
  checkAns(userSequence.length - 1);
}

let allBtns = document.querySelectorAll(".btn");

for (btn of allBtns) {
  btn.addEventListener("click", btnPress);
}

function reset() {
  started = false;
  gameSequence = [];
  userSequence = [];
  level = 0;
}
